src/crevette/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shrimps.urls', namespace="shrimps")),
]

src/shrimps/urls.py
from django.urls import path

from shrimps.views import home, give_birth_to_shrimp, shrimp_detail, edit_shrimp
app_name = "shrimps"

urlpatterns = [
    path('', home, name="home"),  # default path (null) so doesn't need any path string
    path('give-birth/', give_birth_to_shrimp, name="give-birth"),
    path('<int:shrimp_id>/detail/', shrimp_detail, name="detail"),
    path('<int:shrimp_id>/edit/', edit_shrimp, name="edit"),
    path('create/', edit_shrimp, name="create"),
]

src/shrimps/models.py
from django.db import models
from django.utils import timezone


class Shrimp(models.Model):
    COLOR_CHOICES = [
        ("pink", "pink"),
        ("white", "white"),
        ("green", "green"),
        ("red", "red"),
        ("purple", "purple"),
        ("rainbow", "rainbow"),
    ]
    name = models.CharField(max_length=126)
    birth_date = models.DateTimeField(default=timezone.now)
    size = models.IntegerField("size (mm)")
    weight = models.IntegerField("weight (g)")
    color = models.CharField(max_length=32, choices=COLOR_CHOICES)
    is_farmed = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.name} the shrimp"

src/shrimps/forms.py
from django.forms import ModelForm
from shrimps.models import Shrimp


class ShrimpForm(ModelForm):
    """Shrimp model form"""

    class Meta:
        model = Shrimp
        fields = "__all__"

src/shrimps/views.py
from random import randint, choice

from django.shortcuts import render, redirect, get_object_or_404

from django.http import HttpResponse
from shrimps.forms import ShrimpForm
from shrimps.models import Shrimp


# Create your views here.


def home(request):
    """home page: display the number of shrimps inside our aquarium"""

    # num_shrimps = len(Shrimp.objects.all())
    num_shrimps = Shrimp.objects.count()
    # Shrimp.objects.all() = SELECT * FROM shrimp
    # Shrimp.objects.all() = SELECT COUNT(*) FROM shrimp

    # calling count() is more efficient than calling len() because
    # count() calls SQL-specific function COUNT which is optimized and returns only a number
    # whereas for len() we need to get all objects from the database and only then do the count locally

    # last_shrimp = Shrimp.objects.order_by('birth_date').last()
    # if last_shrimp is None:
    #     return HttpResponse(f"""There are 0 shrimps in our aquarium. """)
    # else:
    #     return HttpResponse(f"""There are {num_shrimps} shrimps in our aquarium. Last shrimp born is {last_shrimp}""")

    context = {
        "num_total_shrimps": num_shrimps,
        "shrimp_list": Shrimp.objects.all(),
    }
    return render(request, "home.html", context=context)


def give_birth_to_shrimp(request):
    """random shrimp generator: every time the page is loaded generates a new random shrimp"""

    SHRIMP_NAME_LIST = ["Richard", "Gerard", "Niky", "Hubert", "Crevette", "Paul", "Eli", "Evi"]
    # at first generate the random fields, then create a Shrimp model and populate it
    baby_shrimp_weight = randint(10, 400)
    baby_shrimp_size = randint(10, 100)
    baby_shrimp_name = choice(SHRIMP_NAME_LIST)
    baby_shrimp_color = choice(Shrimp.SHRIMP_COLOR_CHOICES)[0]  # takes first element of the returned tuple
    baby_shrimp_is_farmed = bool(randint(0, 1))
    baby_shrimp = Shrimp(name=baby_shrimp_name, size_mm=baby_shrimp_size,
                         weight_g=baby_shrimp_weight, color=baby_shrimp_color, is_farmed=baby_shrimp_is_farmed)
    baby_shrimp.save()

    context = {
        "shrimp": baby_shrimp,
    }

    return render(request, "detail.html", context=context)
    # return HttpResponse(f"""The baby shrimp {baby_shrimp.name} is born, weighs {baby_shrimp.weight_g} g and measures {baby_shrimp.size_mm} mm""")


def shrimp_detail(request, shrimp_id):
    """display detail of a particular shrimp"""

    context = {
        "shrimp": Shrimp.objects.filter(id=shrimp_id).first()
    }

    return render(request, "detail.html", context=context)


def edit_shrimp(request, shrimp_id=None):
    """edit details of a particular shrimp"""

    shrimp = Shrimp.objects.filter(id=shrimp_id).first() if shrimp_id else None
    if request.method == "POST":
        form = ShrimpForm(data=request.POST, instance=shrimp)
        if form.is_valid():
            shrimp = form.save()
            return redirect("shrimps:detail", shrimp_id=shrimp.id)
    else:  # in this case it's a create function
        form = ShrimpForm(instance=shrimp)

    return render(request, "edit.html", context={"form": form})

src/shrimps/templates/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'shrimps/style.css' %}">
{% if shrimp == NULL %}
    <h1> Oups, this page does not exist</h1>
{% else %}
    <h1> Details about {{ shrimp.name }}</h1>
    <ul>
        <li><p>Name: {{ shrimp.name }}</p></li>
        <li><p>Size: {{ shrimp.size_mm }} mm</p></li>
        <li><p>Weight: {{ shrimp.weight_g }} g</p></li>
        <li><p>Birth Date: {{ shrimp.birth_date }}</p></li>
        {% if shrimp.is_farmed %}
        <li><p>{{shrimp.name}} is farmed</p></li>
        {% else %}
        <li><p>{{shrimp.name}} is FREE</p></li>
        {% endif %}
    </ul>
{% endif %}

<p> <a class="button" href="{% url 'shrimps:edit' shrimp.id %}" > Edit this shrimp </a></p>
<p> <a class="button" href="{% url 'shrimps:home' %}" > Homepage </a></p>

src/shrimps/templates/edit.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'shrimps/style.css' %}">

<h1>Edit Shrimp</h1>

    <form method="POST" >
        {{form}}
        {% csrf_token %}
        <input type="submit" value="Submit"> <br>
    </form>

src/shrimps/templates/home.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'shrimps/style.css' %}">

<h1>The shrimp aquarium</h1>

{% if num_total_shrimps == 0 %}
    <p> There are currently no shrimps in the aquarium </p> 
{% else %}
    <p> There are {{num_total_shrimps}} shrimps in the aquarium </p> 
    <ul>
    {% for shrimp in shrimp_list%}
        <li> <a class="detail_button" href="{% url 'shrimps:detail' shrimp.id %}" > {{shrimp.name}} </a></li>
    {% endfor %}
    </ul>
{% endif %}

<img src="{% static 'shrimps/images/crevette_img1.jpg' %}" alt="shrimp">
<p> <a class="button" href="{% url 'shrimps:give-birth' %}" > Create a new random shrimp </a></p>
<p> <a class="button" href="{% url 'shrimps:create' %}" > Create a new custom shrimp </a></p>

src/shrimps/templates/shrimps/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'shrimps/style.css' %}">

<h1>{{shrimp.name }} {% if created %} is Born {% else %} detail {% endif %} </h1>

<ul> 
    <li>Name: {{shrimp.name}}</li>
    <li>Weight: {{shrimp.weight}} g</li>
    <li>Size: {{shrimp.size}} mm</li>
    <li>Color: {{shrimp.get_color_display}}</li>
    <li>Birth Date: {{shrimp.birth_date}}</li>
    <li>Is farmed ?: {{shrimp.is_farmed}}</li>
</ul>

<a class="button" href="{% url 'shrimps:home' %}"> Home </a>

src/shrimps/templates/shrimps/give-birth.html
<a href="{% url 'shrimps:home' %}"> Home </a>

A new baby shrimp named {baby_shrimp.name} is born and weighs
                        {baby_shrimp.weight} grams and measures {baby_shrimp.size} mm.

src/shrimps/templates/shrimps/home.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'shrimps/style.css' %}">


<h1>The shrimp aquarium</h1>

<p> There are {{ nb_shrimps }} shrimps in the aquarium </p>

<a id="button-create-random" class="button" href="{% url 'shrimps:give-birth' %}"> Create a random shrimp </a>

<ul>
    {% for shrimp in all_shrimps %}
        <li><a href="{% url 'shrimps:detail' shrimp.id %}">{{shrimp.name}}</a></li>
    {% empty %}
        <li>There is no shrimps in the aquarium</li>
    {% endfor %}
</ul>